### PR TITLE
Add PEM Encoding option

### PR DESCRIPTION
**Pull request by pjlamb12**
Many times you need a PEM encoded public key to authenticate with the certificate. This PR takes the `certificate.raw attribute`, if it's there, and converts it to a base64 string, and then formats it properly. Then it saves it in the `pemEncoded` attribute of the `certificate` object.

In my tests, getting the certificate from an actual authorization server always provided a `.raw` attribute. The tests here, though, mock the certificate, so the `raw` attribute is not on there. But I make sure to only try and encode the `certificate.raw` if it is present.

### CODE REVIEW

**Comment by johncrisostomo** [comment]
@pjlamb12 Thanks for this PR! Will review this after work and then merge it!

**Comment by johncrisostomo** [comment]
Hello again @pjlamb12 , if it is not too much to ask, can you update the tests as well (by just adding to the mock and testing these cases as well) ? Sorry I got a bit busy with work and I think this is an awesome addition that should go on a new npm release.

**Comment by pjlamb12** [comment]
Yes! I'll try and do that tonight.

**Comment by pjlamb12** [comment]
@johncrisostomo I added one test for the raw attribute being on the certificate object and that it is a buffer and equal to what comes back from nodejs.org. The second test makes sure that the pemEncoded attribute is formatted correctly and on the certificate object.

**Comment by pjlamb12** [comment]
I'm not sure why the CI tests aren't passing. It doesn't appear to be from the PR I submitted, but I can't tell for sure.

**Comment by pjlamb12** [comment]
This is the error message:
screenshot 15

It looks like it's from an NPM installed package.

**Comment by johncrisostomo** [comment]
@pjlamb12 Hmm, seems to be only failing on Node v4 and v5. Let me investigate and thank you so much for this! Have a happy holiday!

**Comment by pjlamb12** [comment]
@johncrisostomo sounds great! Thanks!

**Pull request merged**
